### PR TITLE
Parallax jumbotron #45

### PR DESCRIPTION
**Pull request by smokeyblues**

### CODE REVIEW

**Review by chuckb1789 — APPROVED** [review]
Make sure to merge development branch back into your branch before we merge.

**Review by chuckb1789 — CHANGES_REQUESTED** [review]
Pull the development branch in, and fix merge issues.

**Comment by smokeyblues** [comment]
Okay this pull request should be ready to go now.

**Review by chuckb1789 — APPROVED** [review]
Looks good!

**Pull request merged**
