### PR TITLE
40 kombucha prod savory peach div

### PR DESCRIPTION
**Pull request by jennPeavler**
This issue had a PR that was merged and closed; however, it wasn't done correctly bc I didn't understand the problem.  Redid the issue correctly this time.

### CODE REVIEW

**Review by chuckb1789 — APPROVED** [review]
There appears to be a merge conflict.

**Review by chuckb1789 — CHANGES_REQUESTED** [review]
Could you resolve the merge conflicts? 

You can do this by pulling in the development branch.
```git pull origin development```

Then you can resolve in Atom. I use a package called [merge-conflicts](https://atom.io/packages/merge-conflicts)

**Comment by jennPeavler** [comment]
I resolved all merge conflicts.  I just did it in gitHub, so it should be all set to go.

**Review by chuckb1789 — APPROVED** [review]
Thanks! Looks great.

**Pull request merged**
